### ISSUE TITLE
请求邀请进入项目组织

### ISSUE THREAD

**Issue by FoxMikoRan** [acygen/PCRCalculator#6]
您好我是pcr玩家也在尝试使用unity，我对JJC模拟战斗模块很感兴趣，想加入您的plasticscm项目组织，我的unity账号邮箱是735752997@qq.com，需要您的邀请

**Comment by nighcate** [comment]
928157563@qq.com，麻烦也邀请一下我，谢谢~

**Comment by xebecWatch** [comment]
risifife@getnada.com 带一个

**Comment by SoKae1** [comment]
ekespnofs@gmail.com  请邀请 , 谢谢.

**Comment by MalangGood** [comment]
lalala@ruu.kr , thankyou

**Comment by limgw97** [comment]
limgw977@gmail.com plz

**Comment by limgw97** [comment]
limgw977@gmail.com plz invite me! Thank you!

**Comment by Joliev02** [comment]
bee_joliev@hotmail.com Ty

**Comment by 964788339** [comment]
964788339@qq.com可以邀请下吗，谢谢

**Comment by Phoenix4438** [comment]
chks6233@gmail.com 拜托您邀请一下。谢谢。

**Comment by r3b0rn10x** [comment]
谷歌盘资源的模拟器很多bug，excel不能导出。JJC没得模拟！要是能进入组织那多好。

**Comment by acygen** [comment]
已经给各位邮箱发送邀请链接，注意必须在中文unity注册账号才能找到项目，注册unity国际版账号是找不到项目的。

**Comment by sanquanjun** [comment]
> 已经给各位邮箱发送邀请链接，注意必须在中文unity注册账号才能找到项目，注册unity国际版账号是找不到项目的。

请问是否可以拉我进项目组？sanquanjun@qq.com
感谢
